name: paged_vertical_calendar_example
description: A simple example showing several ways this package can be used to implement calendar related interfaces.
homepage: https://github.com/casvanluijtelaar/paged_vertical_calendar.git
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  paged_vertical_calendar:
    path: ../
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
